services:
  recollect-mcp:
    container_name: recollect-mcp
    build:
      context: ./recollect-mcp
    ports:
      - "9090:9090"
    env_file:
      - ./recollect-mcp/.env
    networks:
      - agent-network
    environment:
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - ./.vscode:/app/.vscode
      - shared_media:/app/shared_media
      - ~/.cache:/root/.cache
      - ~/.cache/huggingface:/root/.cache/huggingface
    
    deploy:
      resources:
        limits:
          cpus: '4' 
          memory: 4G   
        reservations:
          cpus: '4'    
          memory: 4G   

  recollect-api:
    container_name: recollect-api
    build:
      context: ./recollect-api
    ports:
      - "8080:8080"
    environment:
      - DISABLE_NEST_ASYNCIO=True
    env_file:
      - ./recollect-api/.env
    networks:
      - agent-network
    depends_on:
      - recollect-mcp
    volumes:
      - shared_media:/app/shared_media
      - ./.vscode:/app/.vscode
  recollect-ui:
    container_name: recollect-ui
    build:
      context: ./recollect-ui
    ports:
      - "3000:3000"
    depends_on:
      - recollect-api
      - recollect-mcp
    networks:
      - agent-network
    volumes:
      - shared_media:/app/shared_media

networks:
  agent-network:
    name: agent-network

volumes:
  shared_media:
    name: shared_media